### ISSUE TITLE
one_shot_demo copy error on pip install

### ISSUE THREAD

**Issue by senoadiw** [GeoNode/django-osgeo-importer#106]
Hi,

I'm getting the following error on pip install:

    error: can't copy 'osgeo_importer/static/osgeo_importer/img/one_shot_demo': doesn't exist or not a regular file

The error appears both when installing from this repo and from pypi.

Cheers

**Comment by JivanAmara** [comment]
Hi senoadiw, I'm able to install without a problem; can you offer some more details, such as the install output, platform, python version, if you're using a virtualenv or installing directly to system site-packages.

**Comment by senoadiw** [comment]
Hi @JivanAmara, I'm trying django-osgeo-importer on a GeoNode docker https://github.com/senoadiw/docker-geonode-oauth/tree/osgeo_importer.

The django container only has geonode==2.5.9 installed by default with Python 2.7.9 (it's based on https://github.com/GeoNode/django-docker/blob/geonode/Dockerfile). Here are the logs:

git clone https://github.com/senoadiw/docker-geonode-oauth.git
cd docker-geonode-oauth
git checkout osgeo_importer
docker-compose build
docker run -it -v "$(pwd)":/usr/src/app dockergeonodeoauth_django bash

pip list: [pip_list.txt](https://github.com/GeoNode/django-osgeo-importer/files/750184/pip_list.txt)

pip install django-osgeo-importer: [pip_install.txt](https://github.com/GeoNode/django-osgeo-importer/files/750188/pip_install.txt)

**Comment by JivanAmara** [comment]
Hi @senoadiw, I haven't had a chance to check your issue specifically but there is a new pypi package (0.1.1a1) that could address this issue.  Would you check & confirm if this issue has been resolved?

**Comment by senoadiw** [comment]
@JivanAmara I tried the new package and can confirm that it now installs properly. Here's the log on the docker container:

pip install django-osgeo-importer: [pip_install.txt](https://github.com/GeoNode/django-osgeo-importer/files/759688/pip_install.txt)

I'll close this issue, thanks for the fix!

Cheers

**Comment by JivanAmara** [comment]
More thanks to @BerryDaniel than me for this fix, but glad you're in the clear :)
