### ISSUE TITLE
Ignore non-layer files.

### ISSUE THREAD

**Issue by JivanAmara** [GeoNode/django-osgeo-importer#132]
Many packages & zip files contain extra files that shouldn't/can't be processed as layer data. These should be ignored instead of causing errors.

Examples:

- .shp.xml .sbn from shapefile .zips
- __MACOSX directory from zips made on Macs.
- .txt files with descriptions, licenses, or metadata

**Comment by Coop56** [comment]
Closing as this was completed awhile back.
