### ISSUE TITLE
Before bumping to Geonode 2.7.x, we'll need to bump Angular from 1.3 to 1.4

### ISSUE THREAD

**Issue by emilyashley** [GeoNode/django-osgeo-importer#183]
Geonode 2.7.x uses Angular 1.4.0. [ref](https://github.com/GeoNode/geonode/blob/2.7.x/geonode/static/bower.json#L26)

Whenever django-osgeo-importer is ready to bump from Geonode 2.6.x to 2.7.x we'll also need to bump Angular. Making note of this, and offering to handle that part of the bump when the time comes.

For our [MapStory](https://github.com/MapStory) project using this importer we've created a branch to bump this importer from Angular 1.3 to 1.6 [here](https://github.com/GeoNode/django-osgeo-importer/tree/angular-1.6) and I've included all backwards compatible changes in the importer master branch via https://github.com/GeoNode/django-osgeo-importer/commit/c17407caba5c39af01cbef5e25c47c1323eba93a.

The bump to 1.4 will require bumping angular-resource, angular-cookies, and angular-mocks in the package.json and committing them in the `/static/osgeo_importer/js/` directory because they are included in the {% _importer_scripts.html %} template assets.

**Comment by Coop56** [comment]
Closing this now as master has been bumped to Angular 1.6.5.
