### ISSUE TITLE
Setup coveralls.io on this fork

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/django-osgeo-importer#46]

**Comment by harts-boundless** [comment]
Our recent work on this was here: https://github.com/boundlessgeo/django-osgeo-importer/pull/41

**Comment by jj0hns0n** [comment]
needs to be setup on the main GeoNode fork now. But no rush.

**Comment by harts-boundless** [comment]
Understood, just wanted to provide the link for reference/context of anyone who wants to work on this

**Comment by sarasafavi** [comment]
This was completed in https://github.com/GeoNode/django-osgeo-importer/pull/53 & other (non-PR) work
