### ISSUE TITLE
GeoServer-independent use of Importer

### ISSUE THREAD

**Issue by sarasafavi** [GeoNode/django-osgeo-importer#58]
See also: https://github.com/boundlessgeo/django-osgeo-importer/pull/43

Currently layer import fails without GeoServer handlers listed in IMPORT_HANDLERS - my understanding is that django-osgeo-importer should also work with only GeoNode & not GeoServer available. 

Not sure if this is a pending feature or just lack of documentation - either way, let's fix.

**Comment by harts-boundless** [comment]
This should have been resolved by #65, if so can you close this @sarasafavi

**Comment by sarasafavi** [comment]
Yup, confirmed -- thanks @harts-boundless
